import matplotlib.pyplot as plt
import numpy as np
l=[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10]
a=np.sin(l)
b=np.cos(l)
c=np.tan(l)
d=np.array(l)
e=1/(np.sin(l))
f=1/(np.cos(l))
g=1/(np.tan(l))
####################################################################
'''
plt.plot(a,b)
plt.show()
plt.plot(a,c)
plt.show()
plt.plot(a,(b+c))
plt.show()
plt.plot(a,d)
plt.show()
plt.plot(b,d)
plt.show()
plt.plot(c,d)
plt.show()
plt.plot(b,c)
plt.show()
plt.plot(c,a)
plt.show()
plt.plot(b,a)
plt.show()
plt.plot(a,a)
plt.show()
plt.plot(b,b)
plt.show()
plt.plot(c,c)
plt.show()
plt.plot(d,c)
plt.show()
plt.plot(a,(a+b+c+d))
plt.show()
plt.plot(b,(a+b+c+d))
plt.show()
plt.plot(c,(a+b+c+d))
plt.show()
plt.plot(d,(a+b+c+d))
plt.show()
plt.plot(a,(a*b*c*d))
plt.show()
plt.plot(b,(a*b*c*d))
plt.show()
plt.plot(c,(a*b*c*d))
plt.show()
plt.plot(d,(a*b*c*d))
plt.show()
plt.plot(a,(a-b-c-d))
plt.show()
plt.plot(b,(a-b-c-d))
plt.show()
plt.plot(c,(a-b-c-d))
plt.show()
plt.plot(d,(a-b-c-d))
plt.show()
plt.plot(e,d)
plt.show()
plt.plot(f,d)
plt.show()
plt.plot(g,d)
plt.show()
plt.plot(d,e)
plt.show()
plt.plot(d,f)
plt.show()
plt.plot(d,g)
plt.show()
plt.plot((e*f),(f*g))
plt.show()
plt.plot((a+e),(d*e))
plt.show()
plt.plot((a+g),(d*g),color="brown")
plt.show()
plt.plot((b+f),(d*f))
plt.show()
plt.plot((d+g),(d*g),color="brown")
plt.show()
plt.plot((a+e),(d*e),color="orange")
plt.show()
plt.plot((b+f),(d*f),color="red")
plt.show()
plt.plot((d+a),(d*a),color="black")
plt.show()
plt.plot((d+b),(d*b),color="pink")
plt.show()
plt.plot((d*c),(d+c),color="gray")
plt.show()
plt.plot(((a*d)+(d*c)+(d*e))/((d*b)+(d*f)+(d*g)),((d+a)*(d+c)*(d+e))/((d-b)*(d-f)*(d-g)),color="m")
plt.show()
plt.plot((f+d*g*a+b*e),d)
plt.show()
plt.plot(d,(f*d/g*a+b*e))
plt.show()
plt.plot((d/c),(d+c),color="gray")
plt.show()
plt.plot((b+f),(d/f),color="red")
plt.show()
plt.plot((d+g),(d/g),color="brown")
plt.show()
plt.plot((b/f),(d/f))
plt.show()
plt.plot((d*c),(d-c),color="gray")
plt.show()
plt.plot((b/f),(d*f))
plt.show()
plt.plot((b/e),(d*e))
plt.show()
plt.plot((b/g),(d*g),color="gold")
plt.show()
plt.plot((b/a),(d*a),color="silver")
plt.show()
plt.plot((b/c),(d*c),color="skyblue")
plt.show()
plt.plot((b/(e*b)),(d*f),color="lightgreen")
plt.show()
plt.plot((b/(a*f)),(d*a),color="lightblue")
plt.show()
plt.plot((b/((a+d))),((d*a)-(d+a)),color ="black")
plt.show()
plt.plot((b/((a*f*g*e*c*d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.plot((b/((a/f/g/e/c/d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.plot((b/((a/f/g/e/c/d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f*g*e*c*d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.plot((b*((a/f/g/e/c/d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.plot((b*((a/f/g/e/c/d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.plot((b*((a*f*g*e*c*d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.plot((b*((a*f*g*e*c*d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.plot((b*((a*f*g*e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a/f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b*((a/f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f*g*e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a/f*g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a/f/g/e*c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a/f/g/e/c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f*g/e*c*d))),-((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((c/((a*f*g*e*b*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b*((a*f*g/e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f/g*e/c*d))),((d/a)*(d*a)),color ="black")
plt.show()
plt.plot((b/((a*f/g*e/c*d))),((d/b)/(d*b)),color ="black")
plt.show()
plt.plot((b/((a*f/g/e/c*d))),((d/g)/(d*g)),color ="black")
plt.show()
plt.plot((b/((a*f/g/e/c*d))),((d/g)*(d*g)),color ="black")
plt.show()
plt.plot((b/((a*f/g/e/c*d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.plot((b*((a*f/g/e/c*d))),((d/g)+(d*g)),color ="yellow")
plt.show()
plt.plot((b/((a/f*g/e*c/d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.plot((b*((a/f*g/e*c/d))),((d*g)*(d*g)),color ="black")
plt.show()
plt.plot((b/((a/f/g*e/c/d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.plot((b*((a/f/g*e/c/d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.plot((f/((a/f/g*e/c/d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.plot((f/((a*f/g*e/c*d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.plot((f/((a*b*g*e*c*d))),((d*g)+(d*g)),color ="orange")
plt.show()
plt.plot((f/((a*b*g*e*c*d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.plot((f/((a*b*g*e*c*d))),((d*a)*(d*a)),color ="orange")
plt.show()
plt.plot((f/((a*b*g/e*c*d))),((d*a)*(d*a)),color ="orange")
plt.show()
plt.plot((f/((a*b/g*e/c*d))),((d*a)*(d*g*e)),color ="orange")
plt.show()
plt.plot((f*((a*b/g*e/c*d))),((d*f)/(d*a)),color ="red")
plt.show()
plt.plot((f*((a/b/g/e/c/d))),((d*f)*(d*b)),color ="orange")
plt.show()
plt.plot((f*((a/b/g/e/c/d))),((d*f)/(d*b)),color ="orange")
plt.show()
plt.plot((f/((a*b*g*e*c*d))),((d/f)/(d*f)),color ="orange")
plt.show()
plt.plot((a/((f*b*g*e*c*d))),((d*b)*(d*b)),color ="orange")
plt.show()'''
plt.plot((a*((f*b*g/e*c*d))),((d*g)*(d*g)),color ="green")
plt.show()
