import matplotlib.pyplot as plt
import numpy as np
l=[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,9,10]
a=np.sin(l)
b=np.cos(l)
c=np.tan(l)
d=np.array(l)
e=1/(np.sin(l))
f=1/(np.cos(l))
g=1/(np.tan(l))
###################################################################
plt.scatter(a,b)
plt.show()
plt.scatter(a,c)
plt.show()
plt.scatter(a,(b+c))
plt.show()
plt.scatter(a,d)
plt.show()
plt.scatter(b,d)
plt.show()
plt.scatter(c,d)
plt.show()
plt.scatter(b,c)
plt.show()
plt.scatter(c,a)
plt.show()
plt.scatter(b,a)
plt.show()
plt.scatter(a,a)
plt.show()
plt.scatter(b,b)
plt.show()
plt.scatter(c,c)
plt.show()
plt.scatter(d,c)
plt.show()
plt.scatter(a,(a+b+c+d))
plt.show()
plt.scatter(b,(a+b+c+d))
plt.show()
plt.scatter(c,(a+b+c+d))
plt.show()
plt.scatter(d,(a+b+c+d))
plt.show()
plt.scatter(a,(a*b*c*d))
plt.show()
plt.scatter(b,(a*b*c*d))
plt.show()
plt.scatter(c,(a*b*c*d))
plt.show()
plt.scatter(d,(a*b*c*d))
plt.show()
plt.scatter(a,(a-b-c-d))
plt.show()
plt.scatter(b,(a-b-c-d))
plt.show()
plt.scatter(c,(a-b-c-d))
plt.show()
plt.scatter(d,(a-b-c-d))
plt.show()
plt.scatter(e,d)
plt.show()
plt.scatter(f,d)
plt.show()
plt.scatter(g,d)
plt.show()
plt.scatter(d,e)
plt.show()
plt.scatter(d,f)
plt.show()
plt.scatter(d,g)
plt.show()
plt.scatter((e*f),(f*g))
plt.show()
plt.scatter((a+e),(d*e))
plt.show()
plt.scatter((a+g),(d*g),color="brown")
plt.show()
plt.scatter((b+f),(d*f))
plt.show()
plt.scatter((d+g),(d*g),color="brown")
plt.show()
plt.scatter((a+e),(d*e),color="orange")
plt.show()
plt.scatter((b+f),(d*f),color="red")
plt.show()
plt.scatter((d+a),(d*a),color="black")
plt.show()
plt.scatter((d+b),(d*b),color="pink")
plt.show()
plt.scatter((d*c),(d+c),color="gray")
plt.show()
plt.scatter(((a*d)+(d*c)+(d*e))/((d*b)+(d*f)+(d*g)),((d+a)*(d+c)*(d+e))/((d-b)*(d-f)*(d-g)),color="m")
plt.show()
plt.scatter((f+d*g*a+b*e),d)
plt.show()
plt.scatter(d,(f*d/g*a+b*e))
plt.show()
plt.scatter((d/c),(d+c),color="gray")
plt.show()
plt.scatter((b+f),(d/f),color="red")
plt.show()
plt.scatter((d+g),(d/g),color="brown")
plt.show()
plt.scatter((b/f),(d/f))
plt.show()
plt.scatter((d*c),(d-c),color="gray")
plt.show()
plt.scatter((b/f),(d*f))
plt.show()
plt.scatter((b/e),(d*e))
plt.show()
plt.scatter((b/g),(d*g),color="gold")
plt.show()
plt.scatter((b/a),(d*a),color="silver")
plt.show()
plt.scatter((b/c),(d*c),color="skyblue")
plt.show()
plt.scatter((b/(e*b)),(d*f),color="lightgreen")
plt.show()
plt.scatter((b/(a*f)),(d*a),color="lightblue")
plt.show()
plt.scatter((b/((a+d))),((d*a)-(d+a)),color ="black")
plt.show()
plt.scatter((b/((a*f*g*e*c*d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.scatter((b/((a/f/g/e/c/d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.scatter((b/((a/f/g/e/c/d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f*g*e*c*d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.scatter((b*((a/f/g/e/c/d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.scatter((b*((a/f/g/e/c/d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.scatter((b*((a*f*g*e*c*d))),((d*a)-(d/a)),color ="black")
plt.show()
plt.scatter((b*((a*f*g*e*c*d))),((d/a)-(d*a)),color ="black")
plt.show()
plt.scatter((b*((a*f*g*e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a/f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b*((a/f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f*g*e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f/g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a/f*g/e/c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a/f/g/e*c/d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a/f/g/e/c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f*g/e*c*d))),-((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((c/((a*f*g*e*b*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b*((a*f*g/e*c*d))),((d/a)+(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f/g*e/c*d))),((d/a)*(d*a)),color ="black")
plt.show()
plt.scatter((b/((a*f/g*e/c*d))),((d/b)/(d*b)),color ="black")
plt.show()
plt.scatter((b/((a*f/g/e/c*d))),((d/g)/(d*g)),color ="black")
plt.show()
plt.scatter((b/((a*f/g/e/c*d))),((d/g)*(d*g)),color ="black")
plt.show()
plt.scatter((b/((a*f/g/e/c*d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.scatter((b*((a*f/g/e/c*d))),((d/g)+(d*g)),color ="yellow")
plt.show()
plt.scatter((b/((a/f*g/e*c/d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.scatter((b*((a/f*g/e*c/d))),((d*g)*(d*g)),color ="black")
plt.show()
plt.scatter((b/((a/f/g*e/c/d))),((d*g)+(d*g)),color ="black")
plt.show()
plt.scatter((b*((a/f/g*e/c/d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.scatter((f/((a/f/g*e/c/d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.scatter((f/((a*f/g*e/c*d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.scatter((f/((a*b*g*e*c*d))),((d*g)+(d*g)),color ="orange")
plt.show()
plt.scatter((f/((a*b*g*e*c*d))),((d*g)*(d*g)),color ="orange")
plt.show()
plt.scatter((f/((a*b*g*e*c*d))),((d*a)*(d*a)),color ="orange")
plt.show()
plt.scatter((f/((a*b*g/e*c*d))),((d*a)*(d*a)),color ="orange")
plt.show()
plt.scatter((f/((a*b/g*e/c*d))),((d*a)*(d*g*e)),color ="orange")
plt.show()
plt.scatter((f*((a*b/g*e/c*d))),((d*f)/(d*a)),color ="red")
plt.show()
plt.scatter((f*((a/b/g/e/c/d))),((d*f)*(d*b)),color ="orange")
plt.show()
plt.scatter((f*((a/b/g/e/c/d))),((d*f)/(d*b)),color ="orange")
plt.show()
plt.scatter((f/((a*b*g*e*c*d))),((d/f)/(d*f)),color ="orange")
plt.show()
plt.scatter((a/((f*b*g*e*c*d))),((d*b)*(d*b)),color ="orange")
plt.show()
plt.scatter((a*((f*b*g/e*c*d))),((d*g)*(d*g)),color ="green")
plt.show()
plt.scatter((f*((a*g*c/b*a*e))),((d*g)*(d*g)),color ="red")
plt.show()
plt.scatter(a*((f*b*g/d)),((d*g)*(d*g)),color ="green")
plt.show()
plt.scatter((a*((f*b*g/c))),((d*g)*(d*g)),color ="green")
plt.show()
plt.scatter((a*((f*b*g/e))),((d*g)*(d*g)),color ="green")
plt.show()
plt.scatter((a*((f*b*g/e))),((d*g)+(d*g)),color ="green")
plt.show()
plt.scatter(2*(a*((f*b*g/e))),(((d*e)*(d*e))),color ="green")
plt.show()
plt.scatter((a*((f*b*g/c*d))),((d*a)*(d*b)),color ="green")
plt.show()
plt.scatter((a*((f*b*g/a*d))),((d*a)*(d*b)),color ="green")
plt.show()
plt.scatter((a/((f+b+g/a/d))),((d/a)+(d/b)),color ="blue")
plt.show()
plt.scatter((a/((f-b-g/a/d))),((d/a)-(d/b)),color ="skyblue")
plt.show()
plt.scatter((a*((f+b+g*a*d))),((d*a)+(d*b)),color ="blue")
plt.show()

