import matplotlib.pyplot as plt
import random
a=random.randint(0,100)
b=random.randint(0,100)
c=random.randint(0,100)
d=random.randint(0,100)
e=random.randint(0,100)
f=random.randint(0,100)
g=random.randint(0,100)
h=random.randint(0,100)
i=random.randint(0,100)
j=random.randint(0,100)
k=random.randint(0,100)
l=random.randint(0,100)
m=random.randint(0,100)
n=random.randint(0,100)
o=random.randint(0,100)
sizes = [[a,b,c,d,e ],[f,g,h,i,j],[k,l,m,n,o]]
plt.title("collection chart of 100 rupees for first year")
labels = ['Yash', 'Shruti', 'Adity', 'Tapan','Sanjeet']
plt.bar(labels,sizes[0],color='r',width=0.25)
plt.xlabel("<-- labels -->") 
plt.ylabel("<-- sizes -->")
plt.show()
plt.title("collection chart of 100 rupees for Second year")
plt.bar(labels,sizes[1],color='m',width=0.25)
plt.xlabel("<-- labels -->") 
plt.ylabel("<-- sizes -->")
plt.show()
plt.title("collection chart of 100 rupees for third year")
plt.bar(labels,sizes[2],color='olive',width=0.25)
plt.xlabel("<-- labels -->") 
plt.ylabel("<-- sizes -->")
plt.show()
